version: "3.5"

services:
  bb_postgres:
    image: postgres:15-alpine
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: biblio
      POSTGRES_USER: biblio
      POSTGRES_PASSWORD: biblio

  bb_elastic:
    # TODO: elastic 6.8 doesn't provide an arm64 image. So, we need to use a 
    #   custom image for the time being. Switch this if you are on x86_64.
    # image: elasticsearch:6.8.23
    image: elyalvarado/elasticsearch-arm64:6.8.16
    ports:
      - 9400:9200
    environment:
        - ES_JAVA_OPTS=-Xmx2g -Xms2g
        - discovery.type=single-node
        - xpack.ml.enabled=false
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
    command: >
        /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-icu
        || ./bin/elasticsearch-plugin install https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-6.8.16.zip;
        /usr/local/bin/docker-entrypoint.sh"

  bb_mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=authority
    ports:
      - 27020:27017