version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        - ../.devcontainer.env
    volumes:
      - ../..:/src:cached
      - ./tmp/files:/data/files:cached
    depends_on:
      - db-app
    command:
      - bash
      - -c
      - |
        cd /src
        bash -i -c 'nvm install'
        npm install
        tern status
        tern migrate
        sleep infinity

  oidc:
    image: ugentlib/mock-oidc-server
    restart: unless-stopped
    volumes:
      - ./oidc:/dist/.data
    env_file:
      - ../.devcontainer.env
    network_mode: service:app

  db-app:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: biblio
      POSTGRES_USER: biblio
      POSTGRES_PASSWORD: biblio
      PGPORT: 3051
      # see section on PGDATA in https://hub.docker.com/_/postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblio -d biblio"]
      interval: 30s
      timeout: 10s
      retries: 5

  # NOTE: Elastic 6.8 doesn't provide an arm64 image. So, we need to use a 
  # custom image for the time being. Switch to the container below if you are on x86_64.

  es:
    platform: "linux/amd64"
    image: elasticsearch:6.8.23
    environment:
      - http.host=0.0.0.0
      - http.port=3061
      - ES_JAVA_OPTS=-Xmx512m -Xms512m -server
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - bootstrap.system_call_filter=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: >
        /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-icu
        || ./bin/elasticsearch-plugin install analysis-icu;
        /usr/local/bin/docker-entrypoint.sh"
    healthcheck:
      test: curl -s -f es:3061/_cat/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  #  es:
  #    image: elyalvarado/elasticsearch-arm64:6.8.16
  #    environment:
  #      - http.host=0.0.0.0
  #      - http.port=3061
  #      - ES_JAVA_OPTS=-Xmx512m -Xms512m -server
  #      - discovery.type=single-node
  #      - xpack.ml.enabled=false
  #      - bootstrap.system_call_filter=false
  #    volumes:
  #      - ../tmp/backoffice/es_data:/usr/share/elasticsearch/data
  #    ulimits:
  #      nofile:
  #        soft: 65536
  #        hard: 65536
  #    command: >
  #        /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-icu
  #        || ./bin/elasticsearch-plugin install https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-icu/analysis-icu-6.8.16.zip;
  #        /usr/local/bin/docker-entrypoint.sh"
  #    healthcheck:
  #      test: curl -s -f es:9200/_cat/health >/dev/null || exit 1
  #      interval: 10s
  #      timeout: 5s
  #      retries: 5

volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
