// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CandidateRecord struct {
	ID          string
	Metadata    []byte
	SourceName  string
	SourceID    string
	DateCreated pgtype.Timestamptz
}

type Dataset struct {
	SnapshotID string
	ID         string
	Data       []byte
	DateFrom   pgtype.Timestamptz
	DateUntil  pgtype.Timestamptz
}

type Publication struct {
	SnapshotID string
	ID         string
	Data       []byte
	DateFrom   pgtype.Timestamptz
	DateUntil  pgtype.Timestamptz
}
