// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CandidateRecord struct {
	ID             string
	SourceName     string
	SourceID       string
	SourceMetadata []byte
	Type           string
	Status         string
	Metadata       []byte
	DateCreated    pgtype.Timestamptz
}

type Dataset struct {
	SnapshotID string
	ID         string
	Data       []byte
	DateFrom   pgtype.Timestamptz
	DateUntil  pgtype.Timestamptz
}

type Proxy struct {
	ProxyPersonID string
	PersonID      string
	DateCreated   pgtype.Timestamptz
}

type Publication struct {
	SnapshotID string
	ID         string
	Data       []byte
	DateFrom   pgtype.Timestamptz
	DateUntil  pgtype.Timestamptz
}
