name: Cypress Tests

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
      - name: Uninstall node-sass
        run: npm uninstall node-sass
      - name: Install OS dependencies
        run: |
          apt search libnss3
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Cypress
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress/cypress.config.ts
          record: true
          config: video=true,retries=2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_RESEARCHER_USER_NAME: ${{ secrets.CYPRESS_RESEARCHER_USER_NAME }}
          CYPRESS_RESEARCHER_USER_PASSWORD: ${{ secrets.CYPRESS_RESEARCHER_USER_PASSWORD }}
          CYPRESS_LIBRARIAN_USER_NAME: ${{ secrets.CYPRESS_LIBRARIAN_USER_NAME }}
          CYPRESS_LIBRARIAN_USER_PASSWORD: ${{ secrets.CYPRESS_LIBRARIAN_USER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}